import { useState } from "react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Loader2, Download, Sparkles } from "lucide-react";

export function GenerateImageGoogleButton() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [prompt, setPrompt] = useState("A futuristic cityscape at sunset with flying cars and neon lights");

  const generateImage = async () => {
    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-image-google', {
        body: { prompt }
      });

      if (error) throw error;

      if (data.success && data.imageUrl) {
        setImageUrl(data.imageUrl);
        toast.success("Image generated with Google AI Studio!");
      } else {
        throw new Error(data.error || 'Failed to generate image');
      }
    } catch (error: any) {
      console.error('Error generating image:', error);
      toast.error(error.message || 'Failed to generate image');
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadImage = () => {
    if (!imageUrl) return;
    
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = 'google-ai-generated-image.png';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("Image downloaded!");
  };

  return (
    <div className="space-y-4 p-6 border border-border rounded-lg bg-card">
      <div className="space-y-2">
        <h3 className="text-lg font-semibold flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-primary" />
          Google AI Studio Image Generator
        </h3>
        <p className="text-sm text-muted-foreground">
          Test image generation with your Google API key
        </p>
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">Prompt</label>
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          className="w-full min-h-[100px] p-3 rounded-md border border-input bg-background resize-none"
          placeholder="Describe the image you want to generate..."
        />
      </div>

      <Button
        onClick={generateImage}
        disabled={isGenerating || !prompt.trim()}
        className="w-full"
      >
        {isGenerating ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Generating...
          </>
        ) : (
          <>
            <Sparkles className="w-4 h-4" />
            Generate Image
          </>
        )}
      </Button>

      {imageUrl && (
        <div className="space-y-4">
          <div className="relative rounded-lg overflow-hidden border border-border">
            <img
              src={imageUrl}
              alt="Generated by Google AI Studio"
              className="w-full h-auto"
            />
          </div>
          <Button
            onClick={downloadImage}
            variant="outline"
            className="w-full"
          >
            <Download className="w-4 h-4" />
            Download Image
          </Button>
        </div>
      )}
    </div>
  );
}
