import { useState, useEffect } from 'react';
import { Card } from '@/components/ui/card';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { VisionStageProgressBar } from './VisionStageProgressBar';
import { TemplateFillForm } from './TemplateFillForm';
import { CardRevealModal } from './CardRevealModal';
import { BadgeUnlockModal } from './BadgeUnlockModal';
import { useVisionProgress } from '@/hooks/useVisionProgress';
import { useGameStore } from '@/stores/gameStore';
import { ALL_VISION_TEMPLATES, EVER_GREEN_TIPS, interpolateTemplate, VisionTemplate, getVisionStageLabel } from '@/lib/visionTemplates';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { toast } from 'sonner';
import everGreenImg from '@/assets/advisor-ever-green.png';
import { Loader2 } from 'lucide-react';
import { getBadgeByMilestone } from '@/lib/badgeSystem';
import { useBadges } from '@/hooks/useBadges';
import confetti from 'canvas-confetti';

export function VisionJourneyFlow() {
  const { user } = useAuth();
  const sessionId = useGameStore(state => state.sessionId);
  const level = useGameStore(state => state.level);
  const { subStages, currentSubStage, setCurrentSubStage, saveSubStageProgress, isLoading, stageStartTime } = useVisionProgress();
  
  const [selectedTemplate, setSelectedTemplate] = useState<VisionTemplate | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [showCardReveal, setShowCardReveal] = useState(false);
  const [revealedCard, setRevealedCard] = useState<any>(null);
  const [badgeToShow, setBadgeToShow] = useState<any>(null);
  const [showBadgeModal, setShowBadgeModal] = useState(false);
  
  const { unlockBadge } = useBadges();

  const currentTemplates = ALL_VISION_TEMPLATES[currentSubStage as keyof typeof ALL_VISION_TEMPLATES];
  const currentTips = EVER_GREEN_TIPS[currentSubStage as keyof typeof EVER_GREEN_TIPS];
  const randomTip = currentTips?.[Math.floor(Math.random() * currentTips.length)] || "Let's build something amazing together!";

  // Auto-select first template on mount or when sub-stage changes
  useEffect(() => {
    if (currentTemplates && currentTemplates.length > 0) {
      // Check if there's saved progress
      const currentProgress = subStages.find(s => s.subStageNumber === currentSubStage);
      if (currentProgress?.templateId && !currentProgress.completed) {
        const template = currentTemplates.find(t => t.id === currentProgress.templateId);
        if (template) {
          setSelectedTemplate(template);
          return;
        }
      }
      // Auto-select first template
      setSelectedTemplate(currentTemplates[0]);
    }
  }, [currentSubStage, currentTemplates, subStages]);

  const handleTemplateChange = (template: VisionTemplate) => {
    setSelectedTemplate(template);
  };

  const handleSubmit = async (values: Record<string, string>) => {
    if (!selectedTemplate || !user || !sessionId) return;

    setIsGenerating(true);

    try {
      // Interpolate template
      const cardContent = interpolateTemplate(selectedTemplate, values);

      // Save draft progress first
      await saveSubStageProgress(currentSubStage, selectedTemplate.id, values);

      // Generate card
      const { data, error } = await supabase.functions.invoke('generate-card-from-conversation', {
        body: {
          sessionId,
          messages: [{
            role: 'user',
            content: cardContent
          }],
          currentLevel: level,
          currentPhase: 'VISION',
          eventType: 'VISION_SUBSTAGE_COMPLETE',
          eventContext: {
            stageNumber: currentSubStage,
            templateUsed: selectedTemplate.id,
            filledValues: values
          },
          autoGenerated: true
        }
      });

      if (error) throw error;

      if (data?.card) {
        // Save completed progress with card ID
        await saveSubStageProgress(currentSubStage, selectedTemplate.id, values, data.card.id);
        
        // Record stage completion
        const timeSpent = Math.floor((Date.now() - stageStartTime) / 1000);
        const xpEarned = 50 + (currentSubStage * 25); // 75, 100, 125, 150
        
        const { data: completionData } = await supabase
          .from('stage_completions')
          .insert({
            player_id: user.id,
            session_id: sessionId,
            phase: 'VISION',
            stage_number: currentSubStage,
            stage_label: getVisionStageLabel(currentSubStage),
            xp_earned: xpEarned,
            time_spent_seconds: timeSpent
          })
          .select()
          .single();

        // Update game store
        if (completionData) {
          useGameStore.getState().recordStageCompletion(completionData);
        }

        // Give XP reward
        useGameStore.getState().processGameEvents([{
          type: 'XP_GAIN',
          data: { amount: xpEarned }
        }]);
        
        setRevealedCard(data.card);
        setShowCardReveal(true);

        // Fire custom event for animations
        window.dispatchEvent(new CustomEvent('cardGeneratedWithAnimation', {
          detail: { card: data.card, source: 'vision-flow' }
        }));

        // Notify journey counter update
        window.dispatchEvent(new CustomEvent('journeyProgressUpdated', {
          detail: { 
            newCount: useGameStore.getState().stageHistory.length,
            totalStages: 24 
          }
        }));

        // Check badge unlocks
        const totalCompleted = useGameStore.getState().stageHistory.length;
        const badge = getBadgeByMilestone(totalCompleted);
        
        if (badge && user) {
          const unlocked = await unlockBadge(badge, user.id);
          if (unlocked) {
            useGameStore.getState().processGameEvents([{
              type: 'XP_GAIN',
              data: { amount: badge.xpReward }
            }]);
            setBadgeToShow(badge);
            
            if (badge.rarity === 'legendary') {
              setTimeout(() => {
                confetti({
                  particleCount: 300,
                  spread: 160,
                  origin: { y: 0.6 }
                });
              }, 500);
            }
          }
        }
      }
    } catch (error: any) {
      console.error('Error generating card:', error);
      toast.error('Не удалось создать карточку. Попробуйте ещё раз.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleContinue = async () => {
    setShowCardReveal(false);
    
    // Show badge modal if there's a badge to show
    if (badgeToShow) {
      setTimeout(() => {
        setShowBadgeModal(true);
      }, 300);
    } else {
      proceedToNextStage();
    }
  };

  const proceedToNextStage = async () => {
    setRevealedCard(null);
    setSelectedTemplate(null);

    if (currentSubStage < 4) {
      setCurrentSubStage((currentSubStage + 1) as 1 | 2 | 3 | 4);
    } else {
      // Check if all 4 sub-stages are completed before advancing
      const allStagesComplete = subStages.every(stage => stage.completed && stage.cardId);
      
      if (!allStagesComplete) {
        const incompleteStages = subStages.filter(s => !s.completed).map(s => s.subStageNumber).join(', ');
        toast.error(`Завершите все 4 этапа VISION перед переходом (осталось: ${incompleteStages})`);
        return;
      }

      // All VISION stages complete - transition to RESEARCH
      toast.success('🎉 VISION Phase Complete! Moving to RESEARCH...');
      
      try {
        // Update database phase
        await supabase
          .from('game_sessions')
          .update({ current_phase: 'RESEARCH' })
          .eq('id', sessionId);

        // Update game state
        await supabase
          .from('game_states')
          .insert({
            session_id: sessionId,
            xp: level * 100,
            level: level,
            spores: 0,
            energy: 10,
            streak: 0,
            code_health: 100,
            current_phase: 'RESEARCH',
            current_stage_number: 1,
            current_stage_progress: 0,
            completed_tasks: [],
            current_tasks: [],
            blockers: [],
            milestones: []
          });

        // Update game store
        useGameStore.getState().updateStats({
          currentPhase: 'RESEARCH',
          phaseStage: {
            phase: 'RESEARCH',
            stageNumber: 1,
            stageProgress: 0,
            stageLabel: 'Market Research'
          }
        });

        // Show ChatOnboarding if user hasn't seen it yet
        const { hasSeenChatOnboarding } = useGameStore.getState();
        if (!hasSeenChatOnboarding) {
          setTimeout(() => {
            useGameStore.getState().setShowChatOnboarding(true);
          }, 1000);
        }
      } catch (error) {
        console.error('Failed to transition phase:', error);
        toast.error('Failed to transition phase');
      }
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  if (!currentTemplates || currentTemplates.length === 0) {
    return (
      <div className="flex items-center justify-center h-full">
        <p className="text-muted-foreground">Loading templates...</p>
      </div>
    );
  }

  const currentProgress = subStages.find(s => s.subStageNumber === currentSubStage);

  return (
    <div className="h-full flex flex-col gap-4 overflow-y-auto">
      <VisionStageProgressBar subStages={subStages} currentSubStage={currentSubStage} />

      <Card className="p-6 bg-cyan-500/10 border-2 border-cyan-500/30">
        <div className="flex gap-4">
          <Avatar className="h-12 w-12 border-2 border-cyan-500">
            <AvatarImage src={everGreenImg} alt="Ever Green" />
            <AvatarFallback>EG</AvatarFallback>
          </Avatar>
          <div className="flex-1">
            <h3 className="font-bold text-cyan-500 mb-2">👤 Ever Green</h3>
            <p className="text-sm leading-relaxed italic text-muted-foreground">
              "{randomTip}"
            </p>
          </div>
        </div>
      </Card>

      <Card className="flex-1 p-6">
        <h2 className="text-xl font-bold mb-4">
          {currentSubStage}/4: {selectedTemplate ? selectedTemplate.label : 'Loading...'}
        </h2>

        {selectedTemplate && (
          <TemplateFillForm
            template={selectedTemplate}
            availableTemplates={currentTemplates}
            onTemplateChange={handleTemplateChange}
            initialValues={currentProgress?.filledValues || {}}
            onSubmit={handleSubmit}
            isSubmitting={isGenerating}
          />
        )}
      </Card>

      <CardRevealModal
        open={showCardReveal}
        card={revealedCard}
        stageNumber={currentSubStage}
        onContinue={handleContinue}
      />

      <BadgeUnlockModal 
        badge={badgeToShow}
        isOpen={showBadgeModal}
        onClose={() => {
          setShowBadgeModal(false);
          setBadgeToShow(null);
          proceedToNextStage();
        }}
      />
    </div>
  );
}